version: '2.1'

services:
  christmas-community:
    image: christmas-community
    build: .
    environment:
      NODE_ENV: production
      SITE_TITLE: $SITE_TITLE
      SHORT_TITLE: $SHORT_TITLE
      BULMASWATCH: $BULMASWATCH
      LISTS_PUBLIC: $LISTS_PUBLIC
    ports:
      - 3000:3000
